name: kit_starter3
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

# Dependencies
dependencies:
  animate_do: ^3.3.3
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.6
  device_info_plus: ^9.1.2
  extended_nested_scroll_view: ^6.2.1
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_email_sender: ^6.0.2
  flutter_local_notifications: ^16.3.2
  flutter_localization: ^0.2.0
  flutter_speed_dial: ^7.0.0
  flutter_staggered_animations: ^1.1.1
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  http: ^1.2.1
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  intl: ^0.18.0
  loading_animation_widget: ^1.2.0+4
  mobile_scanner: ^4.0.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  qr_flutter: ^4.1.0
  rxdart: ^0.27.7
  sembast: ^3.6.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  webview_flutter: ^4.7.0
  whatsapp_unilink: ^2.1.0

# change_app_package_name: ^1.1.0
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/icon.png
    - assets/images/splash.png
    - assets/images/icon_trans.png
    - assets/images/brigades/
    - assets/icons/
    - assets/icons/menu1.png
    - assets/icons/menu2.png
    - assets/icons/menu3.png
    - assets/icons/menu4.png
    - assets/icons/menu5.png
    - assets/icons/ic_delete.png
    - assets/icons/ic_cart.png
    - assets/icons/ic_phone.png
    - assets/icons/ic_whatsapp.png
    - assets/icons/ic_world.png

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
